micronaut:
  application:
    name: todo
  server:
    port: 8089
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
            - POST
            - PUT
            - PATCH
            - GET
            - DELETE
    context-path: /api
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: todo
    password: todo
    dialect: org.hibernate.dialect.Oracle10gDialect
jpa:
  default:
    packages-to-scan:
      - 'test.app'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true